version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
  - requirements: requirements.txt

# Additional (downloadable) formats of the documentation to be built, apart
# from the default HTML.
formats:
- htmlzip
